import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  getArray: (key: string) => string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.features": "Características",
    "nav.pricing": "Precios",
    "nav.login": "Iniciar Sesión",
    "nav.signup": "Registrarse",
    
    // Hero Section
    "hero.title": "Tu Coach Nutricional con IA",
    "hero.subtitle": "Menús personalizados, recetas deliciosas y una IA que te guía hacia tus objetivos de salud",
    "hero.cta": "Comienza Gratis",
    "hero.trial": "Prueba 4 días gratis",
    
    // Stats
    "stats.users": "Usuarios activos",
    "stats.meals": "Comidas generadas",
    "stats.rating": "Calificación",
    "stats.success": "Éxito comprobado",
    
    // Features
    "features.title": "Todo lo que necesitas para transformar tu alimentación",
    "features.ai.title": "IA Personalizada",
    "features.ai.desc": "Menús adaptados a tus objetivos y preferencias",
    "features.recipes.title": "Recetas Deliciosas",
    "features.recipes.desc": "Comidas saludables que te encantarán",
    "features.goals.title": "Alcanza tus Metas",
    "features.goals.desc": "Bajar grasa, ganar músculo o comer saludable",
    "features.time.title": "Ahorra Tiempo",
    "features.time.desc": "Lista de compras automática cada semana",
    
    // How it works
    "how.title": "Cómo funciona",
    "how.step1.title": "Cuéntanos tus objetivos",
    "how.step1.desc": "Responde unas preguntas sobre tu estilo de vida y metas",
    "how.step2.title": "IA genera tu menú",
    "how.step2.desc": "Recibe un plan semanal personalizado al instante",
    "how.step3.title": "Disfruta y progresa",
    "how.step3.desc": "Sigue tu plan, chatea con tu coach y alcanza tus metas",
    
    // Pricing
    "pricing.title": "Elige tu plan perfecto",
    "pricing.subtitle": "Comienza con 4 días gratis. Cancela cuando quieras.",
    "pricing.month": "mes",
    "pricing.cta": "Comenzar ahora",
    "pricing.comingSoon": "Próximamente",
    "pricing.mostPopular": "Más Popular",
    "pricing.selectPlan": "Seleccionar Plan",
    "pricing.processing": "Procesando...",
    "pricing.pageTitle": "Elige tu plan de nutrición",
    "pricing.pageSubtitle": "Comienza tu viaje hacia una mejor alimentación",
    "pricing.allPlansInclude": "Todos los planes incluyen acceso completo a la plataforma",
    "pricing.cancelAnytime": "Puedes cancelar en cualquier momento",
    "pricing.trialAllPlans": "4 días de prueba gratis en todos los planes",
    "pricing.cancelNoCommitment": "Cancela en cualquier momento sin compromiso",
    
    // Hero extras
    "hero.noCardRequired": "Sin tarjeta requerida",
    "hero.trialDays": "4 días de prueba",
    "hero.cancelAnytime": "Cancela cuando quieras",
    
    // Testimonials
    "testimonials.title": "Lo que dicen nuestros usuarios",
    "testimonials.1.name": "María González",
    "testimonials.1.role": "Bajó 8kg en 2 meses",
    "testimonials.1.text": "Chefly.AI cambió mi vida. Los menús son deliciosos y fáciles de seguir. ¡Perdí peso sin sufrir!",
    "testimonials.2.name": "Carlos Ramírez",
    "testimonials.2.role": "Ganó 5kg de músculo",
    "testimonials.2.text": "Como atleta, necesitaba una nutrición precisa. La IA me creó el plan perfecto para mis entrenamientos.",
    "testimonials.3.name": "Ana Martínez",
    "testimonials.3.role": "Mejoró su salud",
    "testimonials.3.text": "Tengo diabetes y el coach nutricional me ayudó a comer mejor. Mis análisis mejoraron increíblemente.",
    
    // Contact
    "contact.title": "¿Tienes preguntas?",
    "contact.subtitle": "Envíanos un mensaje y te responderemos pronto",
    "contact.form.title": "Envíanos un mensaje",
    "contact.form.subtitle": "Completa el formulario y te responderemos lo antes posible",
    "contact.form.name": "Nombre completo",
    "contact.form.email": "Correo electrónico",
    "contact.form.subject": "Asunto",
    "contact.form.message": "Mensaje",
    "contact.form.submit": "Enviar mensaje",
    "contact.form.success": "¡Mensaje enviado!",
    "contact.form.successDesc": "Gracias por contactarnos. Revisaremos tu mensaje y te responderemos pronto.",
    "contact.form.sendAnother": "Enviar otro mensaje",
    "contact.form.error": "Error al enviar el mensaje",
    "contact.form.errorDesc": "Por favor, inténtalo de nuevo más tarde.",
    "contact.validation.nameRequired": "El nombre es requerido",
    "contact.validation.nameMax": "El nombre debe tener máximo 100 caracteres",
    "contact.validation.emailInvalid": "Email inválido",
    "contact.validation.emailMax": "El email debe tener máximo 255 caracteres",
    "contact.validation.subjectRequired": "El asunto es requerido",
    "contact.validation.subjectMax": "El asunto debe tener máximo 200 caracteres",
    "contact.validation.messageMin": "El mensaje debe tener al menos 10 caracteres",
    "contact.validation.messageMax": "El mensaje debe tener máximo 2000 caracteres",
    
    // Auth
    "auth.welcome": "Bienvenido a",
    "auth.subtitle": "Tu entrenador alimenticio con IA",
    "auth.login": "Iniciar Sesión",
    "auth.signup": "Crear Cuenta",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.accountCreated": "¡Cuenta creada!",
    "auth.accountCreatedDesc": "Bienvenido a Chefly.AI. Configuremos tus preferencias.",
    "auth.welcomeBack": "¡Bienvenido de nuevo!",
    "auth.welcomeBackDesc": "Iniciando sesión...",
    "auth.error": "Error",
    "auth.loginError": "Error al iniciar sesión",
    "auth.invalidEmail": "Correo electrónico inválido",
    "auth.invalidPassword": "Contraseña inválida",
    "auth.passwordLength": "La contraseña debe tener entre 8 y 128 caracteres",
    "auth.backToHome": "Volver al inicio",
    "auth.tagline": "Tu entrenador alimenticio personal",
    "auth.accessAccount": "Accede a tu cuenta",
    "auth.trialInfo": "Prueba gratis por 4 días sin tarjeta requerida",
    "auth.emailPlaceholder": "tu@email.com",
    "auth.passwordPlaceholder": "Mínimo 8 caracteres",
    "auth.freeTrial": "Prueba gratuita de 4 días",
    "auth.noCreditCard": "Sin tarjeta de crédito requerida",
    "auth.termsAgree": "Al registrarte, aceptas nuestros",
    "auth.termsLink": "Términos y Condiciones",
    "auth.and": "y",
    "auth.privacyLink": "Política de Privacidad",
    
    // FAQ
    "faq.title": "Preguntas Frecuentes",
    "faq.subtitle": "Encuentra respuestas a las preguntas más comunes sobre Chefly.AI",
    "faq.backToHome": "Volver al inicio",
    
    // Common
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.close": "Cerrar",
    "common.back": "Volver",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.finish": "Finalizar",
    
    // Sidebar
    "sidebar.dashboard": "Dashboard",
    "sidebar.progress": "Progreso Nutricional",
    "sidebar.achievements": "Logros y Medallas",
    "sidebar.challenges": "Desafíos Diarios",
    "sidebar.leaderboard": "Clasificación",
    "sidebar.coach": "Coach IA",
    "sidebar.subscription": "Mi Suscripción",
    "sidebar.affiliates": "Afiliados",
    "sidebar.admin": "Administración",
    "sidebar.logout": "Cerrar sesión",
    "sidebar.menu": "Menú Principal",
    "sidebar.logoutSuccess": "Sesión cerrada",
    "sidebar.logoutSuccessDesc": "Has cerrado sesión exitosamente",
    
    // Dashboard
    "dashboard.days": ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    "dashboard.meals.breakfast": "Desayuno",
    "dashboard.meals.lunch": "Almuerzo",
    "dashboard.meals.dinner": "Cena",
    "dashboard.welcome": "¡Bienvenido de nuevo!",
    "dashboard.welcomeMessage": "Aquí está tu plan nutricional de la semana",
    "dashboard.trialExpired": "Tu periodo de prueba ha terminado",
    "dashboard.trialExpiredDesc": "Suscríbete para continuar usando Chefly.AI",
    "dashboard.subscribe": "Suscribirse ahora",
    "dashboard.stats": "Tus Estadísticas",
    "dashboard.level": "Nivel",
    "dashboard.totalPoints": "Puntos Totales",
    "dashboard.currentStreak": "Racha Actual",
    "dashboard.longestStreak": "Racha Más Larga",
    "dashboard.mealsCompleted": "Comidas Completadas",
    "dashboard.days_one": "día",
    "dashboard.days_other": "días",
    "dashboard.weeklyPlan": "Menú Semanal",
    "dashboard.generateNew": "Generar Nuevo Plan",
    "dashboard.generating": "Generando plan personalizado...",
    "dashboard.aiThinking": "La IA está creando tu menú perfecto",
    "dashboard.noMealPlan": "No hay plan de comidas",
    "dashboard.createFirst": "Genera tu primer plan semanal personalizado basado en tus preferencias nutricionales",
    "dashboard.generatePlan": "Generar plan ahora",
    "dashboard.noPreferences": "Primero configura tus preferencias",
    "dashboard.setupPreferences": "Ajustar preferencias",
    "dashboard.todaySummary": "Resumen de Hoy",
    "dashboard.completedMeals": "Comidas Completadas",
    "dashboard.viewSummary": "Ver Resumen del Día",
    "dashboard.quickActions": "Acciones Rápidas",
    "dashboard.chatCoach": "Hablar con coach",
    "dashboard.viewProgress": "Ver Progreso",
    "dashboard.editPreferences": "Ajustar preferencias",
    "dashboard.trendingUp": "Tendencia al alza",
    "dashboard.errorGenerate": "Error al generar el plan",
    "dashboard.tryAgain": "No se pudo generar el plan de comidas. Por favor, intenta de nuevo más tarde.",
    "dashboard.planGenerated": "¡Menú generado!",
    "dashboard.planReady": "Tu nuevo plan semanal fue creado con IA",
    "dashboard.planCached": "¡Menú listo!",
    "dashboard.planCachedDesc": "Se reutilizó un menú existente con tus preferencias",
    "dashboard.mealCompleted": "¡Ya completaste esta comida!",
    "dashboard.keepStreak": "Sigue así, vas muy bien 💪",
    "dashboard.pointsEarned": "+10 pts",
    "dashboard.errorComplete": "No se pudo marcar la comida como completada",
    "dashboard.unlocked": "Desbloqueado",
    "dashboard.viewDetails": "Ver detalles",
    "dashboard.swapMeal": "Cambiar comida",
    "dashboard.markComplete": "Marcar como completada",
    "dashboard.completed": "¡Completada!",
    "dashboard.limitReached": "Límite alcanzado",
    "dashboard.limitReachedDesc": "Has alcanzado el límite de {{limit}} planes mensuales. Actualiza al plan Intermedio para planes ilimitados.",
    "dashboard.upgradePlan": "Actualizar Plan",
    "dashboard.loading": "Cargando tu panel de nutrición...",
    "dashboard.mascotGreeting": "¡Hola! Soy tu compañero",
    "dashboard.mascotHelp": "Te ayudaré a lograr tus metas de nutrición 🎯",
    "dashboard.mealsThisWeek": "Comidas esta semana",
    "dashboard.plansGenerated": "Planes generados",
    "dashboard.lastUpdate": "Última actualización",
    "dashboard.generateNewPlan": "Generar nuevo plan semanal",
    "dashboard.unlockFeatures": "Desbloquea todas las funciones",
    "dashboard.withIntermediate": "Con el plan Intermedio puedes:",
    "dashboard.unlimitedPlans": "Generar planes de comida ilimitados",
    "dashboard.swapMeals": "Intercambiar comidas entre días",
    "dashboard.unlimitedChat": "Chat ilimitado con tu coach",
    "dashboard.viewPlans": "Ver planes",
    "dashboard.weekOf": "Semana del",
    "dashboard.meals": "comidas",
    "dashboard.generatingAI": "Generando menú único con IA...",
    "dashboard.waitMessage": "Estamos creando tu plan personalizado con IA. Esto puede tomar hasta 30 segundos...",
    "dashboard.subscriptionSuccess": "¡Suscripción exitosa!",
    "dashboard.subscriptionSuccessDesc": "Tu suscripción ha sido activada. Refrescando estado...",
    "dashboard.tooSoon": "Demasiado pronto",
    "dashboard.waitHours": "Debes esperar {{hours}} hora{{plural}} más antes de generar un nuevo plan.",
    "dashboard.featureUnavailable": "Función no disponible",
    "dashboard.needIntermediate": "Necesitas el plan Intermedio para generar nuevos planes. ¡Actualiza tu plan!",
    "dashboard.needIntermediateSwap": "Necesitas el plan Intermedio para intercambiar comidas. ¡Actualiza tu plan!",
    "dashboard.swapped": "¡Comidas intercambiadas!",
    "dashboard.swappedDesc": "Las comidas se han movido exitosamente",
    "dashboard.portalError": "No se pudo abrir el portal de gestión. Intenta de nuevo.",
    "dashboard.opening": "Abriendo...",
    "dashboard.manageSubscription": "Gestionar suscripción",
    "dashboard.retrying": "Reintentando...",
    "dashboard.attempt": "Intento {{current}} de {{total}}",
    "dashboard.progressToLevel": "Progreso al siguiente nivel",
    "dashboard.points": "puntos",
    "dashboard.intermediatePlan": "Plan Intermedio",
    "dashboard.languageNote": "El idioma del plan depende del idioma seleccionado al generarlo",
    "dashboard.planLanguage": "Idioma del plan",
    
    // Chat
    "chat.title": "Coach Nutricional IA",
    "chat.backToDashboard": "Volver al Dashboard",
    "chat.placeholder": "Escribe tu pregunta sobre nutrición...",
    "chat.send": "Enviar",
    "chat.limitReached": "Límite de mensajes alcanzado",
    "chat.limitReachedDesc": "Has alcanzado el límite de {{limit}} mensajes diarios del plan Básico. Actualiza al plan Intermedio para chat ilimitado.",
    "chat.messagesUsed": "Mensajes usados hoy",
    "chat.messagesLimit": "de {{limit}} diarios",
    "chat.unlimited": "ilimitado",
    "chat.welcome": "¡Hola! Soy tu coach nutricional con IA. ¿En qué puedo ayudarte hoy?",
    "chat.errorSending": "Error al enviar mensaje",
    "chat.errorSendingDesc": "Por favor, inténtalo de nuevo",
    
    // Privacy & Terms
    "privacy.title": "Política de Privacidad",
    "privacy.lastUpdated": "Última actualización",
    "privacy.back": "Volver",
    "terms.title": "Términos y Condiciones",
    "terms.lastUpdated": "Última actualización",
    "terms.back": "Volver",
    
    // NotFound
    "notfound.title": "404",
    "notfound.heading": "Página no encontrada",
    "notfound.message": "Lo sentimos, la página que buscas no existe o ha sido movida.",
    "notfound.goBack": "Volver atrás",
    "notfound.goHome": "Ir al inicio",
    
    // Meal Detail
    "mealDetail.nutritionalInfo": "Información Nutricional",
    "mealDetail.calories": "Calorías",
    "mealDetail.protein": "Proteína",
    "mealDetail.carbs": "Carbohidratos",
    "mealDetail.fats": "Grasas",
    "mealDetail.benefits": "Beneficios",
    "mealDetail.ingredients": "Ingredientes",
    "mealDetail.steps": "Pasos a seguir",
    "mealDetail.swapMeal": "Intercambiar comida",
    "mealDetail.lockedMessage": "Necesitas estar suscrito para intercambiar comidas",
    "mealDetail.breakfast": "Desayuno",
    "mealDetail.lunch": "Almuerzo",
    "mealDetail.dinner": "Cena",
    
    // Swap Meal
    "swapMeal.title": "Intercambiar comida",
    "swapMeal.description": "Selecciona con qué comida quieres intercambiar",
    
    // Challenges
    "challenges.title": "Desafíos Diarios",
    "challenges.subtitle": "Completa desafíos para ganar puntos extra",
    "challenges.noChallenges": "No hay desafíos activos",
    "challenges.generateNew": "Generar nuevos desafíos",
    "challenges.generating": "Generando...",
    "challenges.errorLoading": "No se pudieron cargar los desafíos",
    "challenges.errorGenerating": "No se pudieron generar los desafíos",
    "challenges.challengesGenerated": "¡Desafíos generados!",
    "challenges.newChallenges": "Tienes 3 nuevos desafíos diarios",
    "challenges.complete": "Completar",
    "challenges.completed": "¡Completado!",
    "challenges.progress": "Progreso",
    "challenges.reward": "Recompensa",
    "challenges.bonus": "Bonus",
    "challenges.points": "puntos",
    
    // Achievements
    "achievements.title": "Logros y Medallas",
    "achievements.subtitle": "Desbloquea medallas completando retos",
    "achievements.unlocked": "Desbloqueado",
    "achievements.points": "pts",
    
    // Nutrition Charts
    "nutritionCharts.title": "Progreso Nutricional",
    "nutritionCharts.subtitle": "Visualiza tu evolución en el tiempo",
    "nutritionCharts.weekly": "Semanal (28 días)",
    "nutritionCharts.monthly": "Mensual (12 semanas)",
    "nutritionCharts.calories": "Calorías",
    "nutritionCharts.protein": "Proteínas",
    "nutritionCharts.carbs": "Carbohidratos",
    "nutritionCharts.fats": "Grasas",
    "nutritionCharts.mealsCompleted": "Comidas Completadas",
    "nutritionCharts.noData": "No hay datos disponibles aún. Completa comidas para ver tu progreso.",
    
    // Confirm Plan
    "confirmPlan.title": "¿Generar nuevo plan semanal?",
    "confirmPlan.description": "Esto reemplazará tu plan actual. Elige cómo quieres generar tu nuevo menú:",
    "confirmPlan.cached": "Usar menú existente (Recomendado)",
    "confirmPlan.cachedDesc": "Reutiliza un menú con tus mismas preferencias. No consume créditos de IA. ✨",
    "confirmPlan.new": "Generar menú completamente nuevo",
    "confirmPlan.newDesc": "Crea un menú único con IA. Consume créditos de Lovable AI. 🤖",
    "confirmPlan.cancel": "Cancelar",
    "confirmPlan.generate": "Generar plan",
    "confirmPlan.generating": "Generando...",
    
    // Daily Summary
    "dailySummary.title": "¡Día Completado!",
    "dailySummary.subtitle": "Resumen nutricional de",
    "dailySummary.congrats": "¡Excelente trabajo completando todas tus comidas del día!",
    "dailySummary.totalCalories": "Calorías Totales",
    "dailySummary.kcal": "kcal",
    "dailySummary.proteins": "Proteínas",
    "dailySummary.carbohydrates": "Carbohidratos",
    "dailySummary.fats": "Grasas",
    "dailySummary.motivational": "Mantén este ritmo para alcanzar tus objetivos de salud 💪",
    
    // Celebration Messages
    "dashboard.celebrationMessages": ["¡Excelente! 🎉", "¡Sigue así! 💪", "¡Increíble! ⭐", "¡Eres el mejor! 🏆", "¡Qué pro! 🔥"],
    
    // Subscription Banner
    "subscription.activePlan": "Plan",
    "subscription.active": "Activo",
    "subscription.managePlan": "Gestionar plan",
    "subscription.enjoyBenefits": "Disfruta de todos los beneficios de tu plan",
    "subscription.trialExpiring": "Tu periodo de prueba está por vencer",
    "subscription.daysRemaining": "días restantes",
    "subscription.oneDay": "¡Solo queda 1 día!",
    "subscription.subscribeNow": "Suscribirme ahora",
    "subscription.upgradePrompt": "Suscríbete para continuar disfrutando de todas las funciones",
    
    // Demo
    "demo.badge": "Demo interactiva",
    "demo.title": "Descubre cómo funciona",
    "demo.subtitle": "Sigue el flujo completo desde tu registro hasta tu primer plan de comidas personalizado",
    "demo.startDemo": "Iniciar Demo",
    "demo.restart": "Reiniciar Demo",
    "demo.step1Title": "Paso 1: Bienvenida",
    "demo.step1Desc": "Comenzamos conociendo tus objetivos",
    "demo.step2Title": "Paso 2: Preferencias",
    "demo.step2Desc": "Personalizamos tu experiencia",
    "demo.step3Title": "Paso 3: Generación IA",
    "demo.step3Desc": "Creamos tu plan personalizado",
    "demo.step4Title": "Paso 4: Tu Dashboard",
    "demo.step4Desc": "Accede a tu plan y características",
    
    // Achievement Unlock
    "achievementUnlock.unlocked": "¡Logro Desbloqueado!",
    "achievementUnlock.earned": "Has ganado",
    "achievementUnlock.clickToContinue": "Haz clic para continuar",
    
    // Blog
    "blog.title": "Blog de Nutrición",
    "blog.subtitle": "Consejos, recetas y guías para una vida saludable",
    "blog.readMore": "Leer más",
    "blog.backToBlog": "Volver al blog",
    "blog.relatedArticles": "Artículos relacionados",
    "blog.shareArticle": "Compartir artículo",
    "blog.article1.title": "Guía Completa: Planificación de Comidas para Pérdida de Peso Sostenible",
    "blog.article1.excerpt": "Descubre las estrategias científicamente comprobadas para planificar tus comidas y alcanzar tus metas de peso de forma saludable y duradera.",
    "blog.article1.content": [
      "La planificación de comidas es una de las herramientas más poderosas para lograr una pérdida de peso sostenible. No se trata solo de contar calorías, sino de crear un sistema que te permita tomar decisiones nutritivas de manera consistente.",
      "## ¿Por qué es importante planificar tus comidas?",
      "La planificación elimina la toma de decisiones impulsivas cuando tienes hambre, reduce el estrés relacionado con la alimentación y te ayuda a mantener una nutrición balanceada. Estudios demuestran que las personas que planifican sus comidas tienen un 50% más de éxito en mantener su peso ideal.",
      "## Principios básicos de la planificación nutricional",
      "**1. Equilibrio de macronutrientes:** Asegúrate de incluir proteínas magras, carbohidratos complejos y grasas saludables en cada comida. La proporción ideal varía según tus objetivos, pero una guía general es 40% carbohidratos, 30% proteínas y 30% grasas.",
      "**2. Preparación anticipada:** Dedica 2-3 horas los domingos para preparar ingredientes básicos como arroz integral, pollo a la plancha, vegetales cortados y legumbres cocidas. Esto facilitará el armado de comidas durante la semana.",
      "**3. Variedad nutricional:** Incluye alimentos de todos los colores del arcoíris para asegurar una amplia gama de vitaminas, minerales y antioxidantes. La diversidad también previene el aburrimiento alimentario.",
      "## Estrategias prácticas para el éxito",
      "**Batch cooking:** Cocina grandes cantidades de proteínas y granos una vez por semana. Esto te ahorra tiempo y asegura que siempre tengas opciones saludables disponibles.",
      "**Sistema de contenedores:** Utiliza recipientes de vidrio transparente para visualizar tus comidas preparadas. Etiquétalos con el día y el tipo de comida para mayor organización.",
      "**Snacks inteligentes:** Prepara porciones individuales de frutas, frutos secos y vegetales para evitar el consumo excesivo y tener opciones saludables siempre a mano.",
      "## Ejemplo de plan semanal balanceado",
      "**Lunes:**\n- Desayuno: Avena con frutos rojos y almendras\n- Almuerzo: Ensalada de quinoa con pollo y aguacate\n- Cena: Salmón al horno con brócoli y batata",
      "**Martes:**\n- Desayuno: Smoothie verde con espinacas, plátano y proteína\n- Almuerzo: Bowl de arroz integral con tofu y vegetales salteados\n- Cena: Pechuga de pavo con ensalada mixta y nueces",
      "**Miércoles:**\n- Desayuno: Huevos revueltos con tostada integral y aguacate\n- Almuerzo: Sopa de lentejas con vegetales\n- Cena: Pescado blanco con espárragos y quinoa",
      "## Errores comunes a evitar",
      "**1. Planificar comidas demasiado restrictivas:** Esto lleva a antojos y abandono del plan. Incluye tus alimentos favoritos con moderación.",
      "**2. No considerar tu estilo de vida:** Si viajas frecuentemente o tienes horarios irregulares, adapta tu plan a tu realidad.",
      "**3. Ignorar las señales de hambre:** La planificación no significa rigidez absoluta. Aprende a escuchar a tu cuerpo y ajusta según sea necesario.",
      "## Herramientas y recursos útiles",
      "Aplicaciones como Chefly.AI pueden ayudarte a generar planes personalizados basados en tus preferencias, restricciones dietéticas y objetivos. La inteligencia artificial puede sugerir recetas, crear listas de compras y ajustar las porciones según tus necesidades.",
      "## Conclusión",
      "La planificación de comidas es una habilidad que mejora con la práctica. Comienza con pequeños pasos: planifica solo las cenas de la semana o prepara tus desayunos con anticipación. Con el tiempo, desarrollarás un sistema que funcione perfectamente para ti y te acercará a tus metas de salud de manera sostenible.",
      "Recuerda: el mejor plan es aquel que puedes mantener a largo plazo. Sé flexible, paciente contigo mismo y celebra cada pequeño progreso en tu camino hacia una vida más saludable."
    ],
    "blog.article1.tags": ["pérdida de peso", "planificación", "nutrición", "meal prep"],
    "blog.article1.readTime": "8 min",
    "blog.article1.date": "24 de enero de 2025",
    "blog.article1.author": "Eduardo Zermeño",

    // Affiliate Program Banner
    "affiliateBanner.badge": "Gana Dinero Extra",
    "affiliateBanner.title": "¡Únete al",
    "affiliateBanner.titleHighlight": "Programa de Afiliados",
    "affiliateBanner.titleEnd": "de Chefly!",
    "affiliateBanner.description": "Recomienda Chefly y gana hasta",
    "affiliateBanner.commission": "25% de comisión",
    "affiliateBanner.descriptionEnd": "por cada venta. 100% gratis, sin costos de membresía.",
    "affiliateBanner.feature1Title": "20-25% de comisión",
    "affiliateBanner.feature1Desc": "Por cada venta referida",
    "affiliateBanner.feature2Title": "Pagos cada 15 días",
    "affiliateBanner.feature2Desc": "Retiro mínimo de $200 MXN",
    "affiliateBanner.feature3Title": "Dashboard en tiempo real",
    "affiliateBanner.feature3Desc": "Estadísticas y herramientas de marketing",
    "affiliateBanner.cta": "Comenzar Ahora",
    "affiliateBanner.commissionsMonth": "Comisiones este mes",
    "affiliateBanner.salesMonth": "Ventas este mes",
    "affiliateBanner.level": "Nivel",
    "affiliateBanner.levelProgress": "para nivel",

    // Affiliate Payout Method Setup
    "affiliatePayoutMethod.configured": "Método de Pago Configurado",
    "affiliatePayoutMethod.allSet": "¡Todo listo!",
    "affiliatePayoutMethod.allSetDesc": "Puedes solicitar retiros cuando tengas al menos $200 MXN disponibles. Los pagos se procesarán manualmente por nuestro equipo dentro de 1-3 días hábiles.",
    "affiliatePayoutMethod.setup": "Configurar Método de Pago",
    "affiliatePayoutMethod.setupDesc": "Configura tu método de pago preferido para recibir comisiones",
    "affiliatePayoutMethod.configRequired": "Configuración requerida",
    "affiliatePayoutMethod.configRequiredDesc": "Agrega tu información de pago al realizar tu primera solicitud de retiro. Puedes elegir entre PayPal, transferencia bancaria o SPEI.",
    "affiliatePayoutMethod.available": "Métodos disponibles:",
    "affiliatePayoutMethod.paypal": "PayPal - Retiros rápidos",
    "affiliatePayoutMethod.bankTransfer": "Transferencia Bancaria - A tu cuenta bancaria",
    "affiliatePayoutMethod.spei": "SPEI - Transferencia instantánea en México",

    // Affiliate Payout Request
    "affiliatePayoutRequest.title": "Retirar Saldo",
    "affiliatePayoutRequest.available": "Disponible",
    "affiliatePayoutRequest.processTime": "Procesado en 1-3 días hábiles",
    "affiliatePayoutRequest.amount": "Monto a Retirar (MXN)",
    "affiliatePayoutRequest.amountPlaceholder": "Mínimo $",
    "affiliatePayoutRequest.method": "Método de Pago",
    "affiliatePayoutRequest.methodPaypal": "PayPal",
    "affiliatePayoutRequest.methodBank": "Transferencia Bancaria",
    "affiliatePayoutRequest.methodSpei": "SPEI",
    "affiliatePayoutRequest.submit": "Solicitar retiro",
    "affiliatePayoutRequest.submitting": "Enviando solicitud...",
    "affiliatePayoutRequest.minRequired": "Necesitas al menos",
    "affiliatePayoutRequest.minRequiredEnd": "para solicitar un pago",
    "affiliatePayoutRequest.insufficientAmount": "Monto insuficiente",
    "affiliatePayoutRequest.insufficientAmountDesc": "El monto mínimo de retiro es $",
    "affiliatePayoutRequest.insufficientBalance": "Saldo insuficiente",
    "affiliatePayoutRequest.insufficientBalanceDesc": "No tienes suficiente saldo disponible",
    "affiliatePayoutRequest.success": "¡Solicitud enviada!",
    "affiliatePayoutRequest.successDesc": "Tu solicitud de retiro por ${{amount}} MXN ha sido enviada. Nuestro equipo la procesará en 1-3 días hábiles.",
    "affiliatePayoutRequest.error": "Error",

    // Affiliate Tier Names
    "affiliateTier.bronce": "Bronce",
    "affiliateTier.plata": "Plata",
    "affiliateTier.oro": "Oro",
    "affiliateTier.platino": "Platino",
    "affiliateTier.diamante": "Diamante",

    // Affiliates Landing
    "affiliatesLanding.nav.home": "Inicio",
    "affiliatesLanding.nav.login": "Acceder",
    "affiliatesLanding.hero.badge": "Programa Verificado y Confiable",
    "affiliatesLanding.hero.title": "Programa de Afiliados Chefly",
    "affiliatesLanding.hero.subtitle": "Gana dinero compartiendo la mejor plataforma de planes nutricionales personalizados con IA",
    "affiliatesLanding.hero.cta": "Únete Ahora - Es Gratis",
    "affiliatesLanding.hero.seeHow": "Ver Cómo Funciona",
    "affiliatesLanding.stats.activeAffiliates": "Afiliados Activos",
    "affiliatesLanding.stats.paidOut": "Pagado a Afiliados",
    "affiliatesLanding.stats.sales": "Ventas Generadas",
    "affiliatesLanding.stats.satisfaction": "Tasa de Satisfacción",
    "affiliatesLanding.guarantees.payments": "Pagos Garantizados",
    "affiliatesLanding.guarantees.paymentsDesc": "Pagos puntuales cada vez que lo solicites. Sin trucos ni letras pequeñas.",
    "affiliatesLanding.guarantees.security": "Datos Seguros",
    "affiliatesLanding.guarantees.securityDesc": "Información bancaria y de pago protegida con encriptación de nivel bancario.",
    "affiliatesLanding.guarantees.speed": "Procesamiento Rápido",
    "affiliatesLanding.guarantees.speedDesc": "Pagos procesados en 3-5 días hábiles máximo.",
    "affiliatesLanding.guarantees.transparency": "Transparencia Total",
    "affiliatesLanding.guarantees.transparencyDesc": "Dashboard con métricas en tiempo real. Siempre sabes cuánto has ganado.",
    "affiliatesLanding.commissions.title": "Estructura de Comisiones",
    "affiliatesLanding.commissions.subtitle": "Gana comisiones competitivas por cada suscripción que generes",
    "affiliatesLanding.commissions.commission": "Comisión",
    "affiliatesLanding.commissions.earning": "Ganas por venta",
    "affiliatesLanding.benefits.title": "Beneficios del Programa",
    "affiliatesLanding.benefits.subtitle": "Todas las herramientas que necesitas para tener éxito como afiliado",
    "affiliatesLanding.benefits.attractive": "Comisiones Atractivas",
    "affiliatesLanding.benefits.attractiveDesc": "Gana hasta 25% de comisión por cada venta que generes",
    "affiliatesLanding.benefits.timely": "Pagos Puntuales",
    "affiliatesLanding.benefits.timelyDesc": "Retira tus ganancias cuando alcances el mínimo de $200 MXN",
    "affiliatesLanding.benefits.dashboard": "Dashboard Completo",
    "affiliatesLanding.benefits.dashboardDesc": "Monitorea tus clicks, conversiones y ganancias en tiempo real",
    "affiliatesLanding.benefits.easy": "Fácil de Usar",
    "affiliatesLanding.benefits.easyDesc": "Obtén tu enlace personalizado y comienza a ganar en minutos",
    "affiliatesLanding.tiers.title": "Sistema de Niveles",
    "affiliatesLanding.tiers.subtitle": "Sube de nivel y aumenta tus comisiones mientras generas más ventas",
    "affiliatesLanding.tiers.bonus": "bonificación",
    "affiliatesLanding.tiers.progress": "¡Progresa automáticamente!",
    "affiliatesLanding.tiers.progressDesc": "Tu nivel se actualiza automáticamente cuando alcanzas los requisitos",
    "affiliatesLanding.howItWorks.title": "¿Cómo Funciona?",
    "affiliatesLanding.howItWorks.subtitle": "Comienza a ganar en 4 simples pasos",
    "affiliatesLanding.testimonials.title": "Historias de Éxito",
    "affiliatesLanding.testimonials.subtitle": "Afiliados reales compartiendo sus resultados",
    "affiliatesLanding.faq.title": "Preguntas Frecuentes",
    "affiliatesLanding.faq.subtitle": "Todo lo que necesitas saber sobre el programa",
    "affiliatesLanding.cta.title": "¿Listo para Comenzar?",
    "affiliatesLanding.cta.subtitle": "Únete a cientos de afiliados que ya están ganando con Chefly",
    "affiliatesLanding.cta.button": "Comenzar Ahora",
    "affiliatesLanding.cta.info": "¿Necesitas más información?",
    "affiliatesLanding.cta.contact": "Contacta con nosotros",

    // Affiliates Login
    "affiliatesLogin.title": "Portal de Afiliados",
    "affiliatesLogin.subtitle": "Inicia sesión o crea tu cuenta para acceder al dashboard",
    "affiliatesLogin.alert": "Si aún no eres afiliado, primero crea tu cuenta y luego completa el registro de afiliado.",
    "affiliatesLogin.tabLogin": "Iniciar Sesión",
    "affiliatesLogin.tabSignup": "Crear Cuenta",
    "affiliatesLogin.loginTitle": "Iniciar Sesión",
    "affiliatesLogin.loginDesc": "Accede a tu cuenta de afiliado",
    "affiliatesLogin.signupTitle": "Crear Cuenta",
    "affiliatesLogin.signupDesc": "Crea tu cuenta para registrarte como afiliado",
    "affiliatesLogin.email": "Email",
    "affiliatesLogin.password": "Contraseña",
    "affiliatesLogin.confirmPassword": "Confirmar Contraseña",
    "affiliatesLogin.loginButton": "Iniciar Sesión",
    "affiliatesLogin.loggingIn": "Iniciando sesión...",
    "affiliatesLogin.signupButton": "Crear Cuenta y Continuar",
    "affiliatesLogin.creatingAccount": "Creando cuenta...",
    "affiliatesLogin.moreInfo": "¿Necesitas más información?",
    "affiliatesLogin.error.required": "Campos requeridos",
    "affiliatesLogin.error.requiredDesc": "Por favor completa todos los campos",
    "affiliatesLogin.error.noMatch": "Las contraseñas no coinciden",
    "affiliatesLogin.error.noMatchDesc": "Por favor verifica que ambas contraseñas sean iguales",
    "affiliatesLogin.error.short": "Contraseña muy corta",
    "affiliatesLogin.error.shortDesc": "La contraseña debe tener al menos 6 caracteres",
    "affiliatesLogin.error.notAffiliate": "No eres afiliado",
    "affiliatesLogin.error.notAffiliateDesc": "Esta cuenta no está registrada como afiliado. Por favor regístrate primero.",
    "affiliatesLogin.success.welcome": "¡Bienvenido!",
    "affiliatesLogin.success.welcomeDesc": "Inicio de sesión exitoso",
    "affiliatesLogin.success.created": "¡Cuenta creada!",
    "affiliatesLogin.success.createdDesc": "Ahora completa tu registro de afiliado",

    // Affiliates Register
    "affiliatesRegister.title": "Registro de Afiliado",
    "affiliatesRegister.subtitle": "Completa el formulario para unirte al programa de afiliados",
    "affiliatesRegister.alert": "Necesitas iniciar sesión para registrarte como afiliado.",
    "affiliatesRegister.alertLink": "Inicia sesión aquí",
    "affiliatesRegister.fullName": "Nombre Completo",
    "affiliatesRegister.email": "Email",
    "affiliatesRegister.phone": "Teléfono",
    "affiliatesRegister.country": "País",
    "affiliatesRegister.paymentTitle": "Método de Pago",
    "affiliatesRegister.paymentMethod": "Método Preferido",
    "affiliatesRegister.paypalEmail": "Email de PayPal",
    "affiliatesRegister.bank": "Banco",
    "affiliatesRegister.bankAccount": "Número de Cuenta",
    "affiliatesRegister.clabe": "CLABE Interbancaria",
    "affiliatesRegister.commissionsTitle": "Comisiones:",
    "affiliatesRegister.basicPlan": "Plan Básico: 20% de comisión ($48 MXN por venta)",
    "affiliatesRegister.intermediatePlan": "Plan Intermedio: 25% de comisión ($72.50 MXN por venta)",
    "affiliatesRegister.minPayout": "Pago mínimo: $200 MXN",
    "affiliatesRegister.payoutFrequency": "Pagos procesados cada 15 días",
    "affiliatesRegister.submit": "Enviar Solicitud",
    "affiliatesRegister.processing": "Procesando...",
    "affiliatesRegister.error.loginFirst": "Inicia sesión primero",
    "affiliatesRegister.error.loginFirstDesc": "Necesitas crear una cuenta o iniciar sesión para registrarte como afiliado",
    "affiliatesRegister.success.submitted": "¡Solicitud enviada!",
    "affiliatesRegister.success.submittedDesc": "Tu solicitud será revisada en 1-2 días hábiles",

    // Affiliate Marketing Materials
    "affiliateMarketing.title": "Materiales de Marketing",
    "affiliateMarketing.subtitle": "Descarga banners y copia textos promocionales listos para usar",
    "affiliateMarketing.banners": "Banners HTML",
    "affiliateMarketing.copyCode": "Copiar código",
    "affiliateMarketing.texts": "Textos Promocionales",
    "affiliateMarketing.copyText": "Copiar texto",
    "affiliateMarketing.copied": "¡Copiado!",
    "affiliateMarketing.copiedDesc": "El texto ha sido copiado al portapapeles",
    "affiliateMarketing.textShort": "Texto Promocional - Corto",
    "affiliateMarketing.textLong": "Texto Promocional - Largo",
    "affiliateMarketing.socialPost": "Post para Redes Sociales",

    // Onboarding
    "onboarding.title": "Personaliza tu experiencia",
    "onboarding.subtitle": "Cuéntanos sobre ti para crear tu plan perfecto",
    "onboarding.step": "Paso {{current}} de {{total}}",
    "onboarding.description": "Esta información nos ayudará a personalizar tus menús",
    
    "onboarding.goal.title": "¿Cuál es tu objetivo principal?",
    "onboarding.goal.loseFat": "Bajar grasa",
    "onboarding.goal.gainMuscle": "Ganar músculo",
    "onboarding.goal.eatHealthy": "Comer saludable",
    "onboarding.goal.saveMoney": "Comer barato",
    
    "onboarding.diet.title": "¿Qué tipo de dieta prefieres?",
    "onboarding.diet.omnivore": "Omnívora",
    "onboarding.diet.vegetarian": "Vegetariana",
    "onboarding.diet.vegan": "Vegana",
    "onboarding.diet.keto": "Keto",
    "onboarding.diet.paleo": "Paleo",
    
    "onboarding.activity.title": "¿Cuál es tu nivel de actividad física?",
    "onboarding.activity.description": "Esto nos ayuda a calcular mejor tus necesidades calóricas",
    "onboarding.activity.sedentary": "Sedentario - Poco o ningún ejercicio",
    "onboarding.activity.light": "Ligero - Ejercicio 1-2 días/semana",
    "onboarding.activity.moderate": "Moderado - Ejercicio 3-5 días/semana",
    "onboarding.activity.active": "Activo - Ejercicio 6-7 días/semana",
    "onboarding.activity.veryActive": "Muy activo - Ejercicio intenso diario",
    
    "onboarding.personal.title": "Información personal (opcional)",
    "onboarding.personal.description": "Esto nos ayuda a calcular mejor tus necesidades nutricionales",
    "onboarding.personal.age": "Edad",
    "onboarding.personal.agePlaceholder": "Ej: 25",
    "onboarding.personal.weight": "Peso (kg)",
    "onboarding.personal.weightPlaceholder": "Ej: 70",
    "onboarding.personal.gender": "Género",
    "onboarding.personal.male": "Masculino",
    "onboarding.personal.female": "Femenino",
    "onboarding.personal.other": "Otro",
    
    "onboarding.cooking.title": "¿Cuál es tu nivel de experiencia cocinando?",
    "onboarding.cooking.beginner": "Principiante - Recetas simples",
    "onboarding.cooking.intermediate": "Intermedio - Puedo seguir la mayoría de recetas",
    "onboarding.cooking.advanced": "Avanzado - Me gusta cocinar platos complejos",
    
    "onboarding.budget.title": "¿Cuál es tu presupuesto para comida?",
    "onboarding.budget.low": "Bajo - Ingredientes económicos",
    "onboarding.budget.medium": "Medio - Balance entre precio y calidad",
    "onboarding.budget.high": "Alto - Ingredientes premium",
    "onboarding.time.title": "¿Cuánto tiempo puedes cocinar por comida? (minutos)",
    "onboarding.time.minutes": "{{time}} minutos",
    
    "onboarding.meals.title": "¿Cuántas comidas haces al día?",
    "onboarding.meals.count": "{{count}} comidas",
    "onboarding.servings.title": "¿Para cuántas personas cocinas?",
    "onboarding.servings.person": "{{count}} persona",
    "onboarding.servings.people": "{{count}} personas",
    "onboarding.complexityTitle": "Complejidad de las recetas",
    "onboarding.complexitySimple": "Simple - Pocos pasos y ingredientes",
    "onboarding.complexityModerate": "Moderado - Recetas estándar",
    "onboarding.complexityComplex": "Complejo - Recetas elaboradas",
    
    "onboarding.flavors.title": "¿Qué sabores te gustan?",
    "onboarding.flavors.description": "Selecciona todos los que apliquen",
    "onboarding.flavor.sweet": "Dulce",
    "onboarding.flavor.salty": "Salado",
    "onboarding.flavor.spicy": "Picante",
    "onboarding.flavor.sour": "Ácido",
    "onboarding.flavor.umami": "Umami",
    "onboarding.flavor.bitter": "Amargo",
    
    "onboarding.cuisines.title": "¿Qué tipos de cocina prefieres?",
    "onboarding.cuisines.description": "Selecciona todos los que te gusten",
    "onboarding.cuisine.mexican": "Mexicana",
    "onboarding.cuisine.italian": "Italiana",
    "onboarding.cuisine.asian": "Asiática",
    "onboarding.cuisine.mediterranean": "Mediterránea",
    "onboarding.cuisine.american": "Americana",
    "onboarding.cuisine.vegetarian": "Vegetariana",
    "onboarding.cuisine.healthy": "Saludable",
    
    "onboarding.allergies.title": "¿Tienes alergias?",
    "onboarding.allergies.description": "Nos ayuda a evitar estos ingredientes",
    "onboarding.allergies.placeholder": "Ej: Lactosa, gluten, nueces...",
    "onboarding.allergies.add": "Agregar",
    "onboarding.allergies.tooLong": "Entrada muy larga",
    "onboarding.allergies.tooLongDesc": "La alergia no puede tener más de 100 caracteres",
    "onboarding.allergies.invalid": "Entrada inválida",
    "onboarding.allergies.invalidDesc": "Solo se permiten letras y espacios",
    
    "onboarding.dislikes.title": "¿Hay ingredientes que no te gusten?",
    "onboarding.dislikes.description": "Opcional - Nos ayuda a personalizar mejor",
    "onboarding.dislikes.placeholder": "Ej: Brócoli, cilantro, champiñones...",
    "onboarding.notes.title": "Comentarios adicionales (opcional)",
    "onboarding.notes.placeholder": "¿Algo más que debamos saber? Ej: Horarios preferidos, alimentos favoritos, etc.",
    
    "onboarding.buttons.back": "Atrás",
    "onboarding.buttons.next": "Siguiente",
    "onboarding.buttons.creating": "Guardando...",
    "onboarding.buttons.create": "Crear mi plan personalizado",
    
    "onboarding.toast.requiredFields": "Campos requeridos",
    "onboarding.toast.requiredFieldsDesc": "Por favor completa todos los campos obligatorios",
    "onboarding.toast.perfect": "¡Perfecto!",
    "onboarding.toast.generating": "Generando tu primer menú semanal personalizado...",
    "onboarding.toast.errorGenerating": "Error al generar el menú",
    "onboarding.toast.errorGeneratingDesc": "Podrás generarlo manualmente desde el dashboard",
    "onboarding.toast.created": "¡Menú creado!",
    "onboarding.toast.createdDesc": "Tu plan semanal personalizado está listo",
    "onboarding.toast.error": "Error",
    
    // Cookies
    "cookies.message": "Usamos cookies para analizar el tráfico y mejorar tu experiencia.",
    "cookies.accept": "Aceptar",
    "cookies.decline": "Rechazar",
    "cookies.learnMore": "Más información",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.login": "Log In",
    "nav.signup": "Sign Up",
    
    // Hero Section
    "hero.title": "Your AI Nutrition Coach",
    "hero.subtitle": "Personalized menus, delicious recipes, and an AI that guides you to your health goals",
    "hero.cta": "Start Free",
    "hero.trial": "4-day free trial",
    
    // Stats
    "stats.users": "Active users",
    "stats.meals": "Meals generated",
    "stats.rating": "Rating",
    "stats.success": "Proven success",
    
    // Features
    "features.title": "Everything you need to transform your nutrition",
    "features.ai.title": "Personalized AI",
    "features.ai.desc": "Menus adapted to your goals and preferences",
    "features.recipes.title": "Delicious Recipes",
    "features.recipes.desc": "Healthy meals you'll love",
    "features.goals.title": "Reach Your Goals",
    "features.goals.desc": "Lose fat, gain muscle, or eat healthy",
    "features.time.title": "Save Time",
    "features.time.desc": "Automatic shopping list every week",
    
    // How it works
    "how.title": "How it works",
    "how.step1.title": "Tell us your goals",
    "how.step1.desc": "Answer a few questions about your lifestyle and goals",
    "how.step2.title": "AI generates your menu",
    "how.step2.desc": "Get a personalized weekly plan instantly",
    "how.step3.title": "Enjoy and progress",
    "how.step3.desc": "Follow your plan, chat with your coach, and reach your goals",
    
    // Pricing
    "pricing.title": "Choose your perfect plan",
    "pricing.subtitle": "Start with a 4-day free trial. Cancel anytime.",
    "pricing.month": "month",
    "pricing.cta": "Start now",
    "pricing.comingSoon": "Coming Soon",
    "pricing.mostPopular": "Most Popular",
    "pricing.selectPlan": "Select Plan",
    "pricing.processing": "Processing...",
    "pricing.pageTitle": "Choose your nutrition plan",
    "pricing.pageSubtitle": "Start your journey to better nutrition",
    "pricing.allPlansInclude": "All plans include full platform access",
    "pricing.cancelAnytime": "Cancel anytime",
    "pricing.trialAllPlans": "4-day free trial on all plans",
    "pricing.cancelNoCommitment": "Cancel anytime, no commitment",
    
    // Hero extras
    "hero.noCardRequired": "No card required",
    "hero.trialDays": "4-day trial",
    "hero.cancelAnytime": "Cancel anytime",
    
    // Testimonials
    "testimonials.title": "What our users say",
    "testimonials.1.name": "María González",
    "testimonials.1.role": "Lost 8kg in 2 months",
    "testimonials.1.text": "Chefly.AI changed my life. The menus are delicious and easy to follow. I lost weight without suffering!",
    "testimonials.2.name": "Carlos Ramírez",
    "testimonials.2.role": "Gained 5kg of muscle",
    "testimonials.2.text": "As an athlete, I needed precise nutrition. The AI created the perfect plan for my training.",
    "testimonials.3.name": "Ana Martínez",
    "testimonials.3.role": "Improved her health",
    "testimonials.3.text": "I have diabetes and the nutrition coach helped me eat better. My test results improved incredibly.",
    
    // Contact
    "contact.title": "Have questions?",
    "contact.subtitle": "Send us a message and we'll get back to you soon",
    "contact.form.title": "Send us a message",
    "contact.form.subtitle": "Fill out the form and we'll respond as soon as possible",
    "contact.form.name": "Full name",
    "contact.form.email": "Email address",
    "contact.form.subject": "Subject",
    "contact.form.message": "Message",
    "contact.form.submit": "Send message",
    "contact.form.success": "Message sent!",
    "contact.form.successDesc": "Thank you for contacting us. We'll review your message and respond soon.",
    "contact.form.sendAnother": "Send another message",
    "contact.form.error": "Error sending message",
    "contact.form.errorDesc": "Please try again later.",
    "contact.validation.nameRequired": "Name is required",
    "contact.validation.nameMax": "Name must be at most 100 characters",
    "contact.validation.emailInvalid": "Invalid email",
    "contact.validation.emailMax": "Email must be at most 255 characters",
    "contact.validation.subjectRequired": "Subject is required",
    "contact.validation.subjectMax": "Subject must be at most 200 characters",
    "contact.validation.messageMin": "Message must be at least 10 characters",
    "contact.validation.messageMax": "Message must be at most 2000 characters",
    
    // Auth
    "auth.welcome": "Welcome to",
    "auth.subtitle": "Your AI nutrition coach",
    "auth.login": "Log In",
    "auth.signup": "Create Account",
    "auth.email": "Email address",
    "auth.password": "Password",
    "auth.accountCreated": "Account created!",
    "auth.accountCreatedDesc": "Welcome to Chefly.AI. Let's set up your preferences.",
    "auth.welcomeBack": "Welcome back!",
    "auth.welcomeBackDesc": "Logging in...",
    "auth.error": "Error",
    "auth.loginError": "Login error",
    "auth.invalidEmail": "Invalid email address",
    "auth.invalidPassword": "Invalid password",
    "auth.passwordLength": "Password must be between 8 and 128 characters",
    "auth.backToHome": "Back to home",
    "auth.tagline": "Your personal nutrition coach",
    "auth.accessAccount": "Access your account",
    "auth.trialInfo": "4-day free trial, no credit card required",
    "auth.emailPlaceholder": "your@email.com",
    "auth.passwordPlaceholder": "Minimum 8 characters",
    "auth.freeTrial": "4-day free trial",
    "auth.noCreditCard": "No credit card required",
    "auth.termsAgree": "By signing up, you agree to our",
    "auth.termsLink": "Terms and Conditions",
    "auth.and": "and",
    "auth.privacyLink": "Privacy Policy",
    
    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Find answers to the most common questions about Chefly.AI",
    "faq.backToHome": "Back to home",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.finish": "Finish",
    
    // Sidebar
    "sidebar.dashboard": "Dashboard",
    "sidebar.progress": "Nutrition Progress",
    "sidebar.achievements": "Achievements & Badges",
    "sidebar.challenges": "Daily Challenges",
    "sidebar.leaderboard": "Leaderboard",
    "sidebar.coach": "AI Coach",
    "sidebar.subscription": "My Subscription",
    "sidebar.affiliates": "Affiliates",
    "sidebar.admin": "Administration",
    "sidebar.logout": "Log out",
    "sidebar.menu": "Main Menu",
    "sidebar.logoutSuccess": "Logged out",
    "sidebar.logoutSuccessDesc": "You have successfully logged out",
    
    // Dashboard
    "dashboard.days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "dashboard.meals.breakfast": "Breakfast",
    "dashboard.meals.lunch": "Lunch",
    "dashboard.meals.dinner": "Dinner",
    "dashboard.welcome": "Welcome back!",
    "dashboard.welcomeMessage": "Here's your weekly nutrition plan",
    "dashboard.trialExpired": "Your trial period has ended",
    "dashboard.trialExpiredDesc": "Subscribe to continue using Chefly.AI",
    "dashboard.subscribe": "Subscribe now",
    "dashboard.stats": "Your Stats",
    "dashboard.level": "Level",
    "dashboard.totalPoints": "Total Points",
    "dashboard.currentStreak": "Current Streak",
    "dashboard.longestStreak": "Longest Streak",
    "dashboard.mealsCompleted": "Meals Completed",
    "dashboard.days_one": "day",
    "dashboard.days_other": "days",
    "dashboard.weeklyPlan": "Weekly Menu",
    "dashboard.generateNew": "Generate New Plan",
    "dashboard.generating": "Generating personalized plan...",
    "dashboard.aiThinking": "AI is creating your perfect menu",
    "dashboard.noMealPlan": "No meal plan",
    "dashboard.createFirst": "Generate your first personalized weekly plan based on your nutritional preferences",
    "dashboard.generatePlan": "Generate plan now",
    "dashboard.noPreferences": "Set up your preferences first",
    "dashboard.setupPreferences": "Adjust preferences",
    "dashboard.todaySummary": "Today's Summary",
    "dashboard.completedMeals": "Completed Meals",
    "dashboard.viewSummary": "View Day Summary",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.chatCoach": "Talk to coach",
    "dashboard.viewProgress": "View Progress",
    "dashboard.editPreferences": "Adjust preferences",
    "dashboard.trendingUp": "Trending up",
    "dashboard.errorGenerate": "Error generating plan",
    "dashboard.tryAgain": "Could not generate meal plan. Please try again later.",
    "dashboard.planGenerated": "Menu generated!",
    "dashboard.planReady": "Your new weekly plan was created with AI",
    "dashboard.planCached": "Menu ready!",
    "dashboard.planCachedDesc": "Reused an existing menu with your preferences",
    "dashboard.mealCompleted": "You already completed this meal!",
    "dashboard.keepStreak": "Keep it up, you're doing great 💪",
    "dashboard.pointsEarned": "+10 pts",
    "dashboard.errorComplete": "Could not mark meal as completed",
    "dashboard.unlocked": "Unlocked",
    "dashboard.viewDetails": "View details",
    "dashboard.swapMeal": "Swap meal",
    "dashboard.markComplete": "Mark as completed",
    "dashboard.completed": "Completed!",
    "dashboard.limitReached": "Limit reached",
    "dashboard.limitReachedDesc": "You've reached the limit of {{limit}} monthly plans. Upgrade to Intermediate plan for unlimited plans.",
    "dashboard.upgradePlan": "Upgrade Plan",
    "dashboard.loading": "Loading your nutrition panel...",
    "dashboard.mascotGreeting": "Hi! I'm your companion",
    "dashboard.mascotHelp": "I'll help you achieve your nutrition goals 🎯",
    "dashboard.mealsThisWeek": "Meals this week",
    "dashboard.plansGenerated": "Plans generated",
    "dashboard.lastUpdate": "Last update",
    "dashboard.generateNewPlan": "Generate new weekly plan",
    "dashboard.unlockFeatures": "Unlock all features",
    "dashboard.withIntermediate": "With the Intermediate plan you can:",
    "dashboard.unlimitedPlans": "Generate unlimited meal plans",
    "dashboard.swapMeals": "Swap meals between days",
    "dashboard.unlimitedChat": "Unlimited chat with your coach",
    "dashboard.viewPlans": "View plans",
    "dashboard.weekOf": "Week of",
    "dashboard.meals": "meals",
    "dashboard.generatingAI": "Generating unique menu with AI...",
    "dashboard.waitMessage": "We're creating your personalized plan with AI. This may take up to 30 seconds...",
    "dashboard.subscriptionSuccess": "Subscription successful!",
    "dashboard.subscriptionSuccessDesc": "Your subscription has been activated. Refreshing status...",
    "dashboard.tooSoon": "Too soon",
    "dashboard.waitHours": "You must wait {{hours}} more hour{{plural}} before generating a new plan.",
    "dashboard.featureUnavailable": "Feature unavailable",
    "dashboard.needIntermediate": "You need the Intermediate plan to generate new plans. Upgrade your plan!",
    "dashboard.needIntermediateSwap": "You need the Intermediate plan to swap meals. Upgrade your plan!",
    "dashboard.swapped": "Meals swapped!",
    "dashboard.swappedDesc": "Meals have been moved successfully",
    "dashboard.portalError": "Could not open management portal. Try again.",
    "dashboard.opening": "Opening...",
    "dashboard.manageSubscription": "Manage subscription",
    "dashboard.retrying": "Retrying...",
    "dashboard.attempt": "Attempt {{current}} of {{total}}",
    "dashboard.progressToLevel": "Progress to next level",
    "dashboard.points": "points",
    "dashboard.intermediatePlan": "Intermediate Plan",
    "dashboard.languageNote": "The plan language depends on the language selected when generating it",
    "dashboard.planLanguage": "Plan language",
    
    // Chat
    "chat.title": "AI Nutrition Coach",
    "chat.backToDashboard": "Back to Dashboard",
    "chat.placeholder": "Type your nutrition question...",
    "chat.send": "Send",
    "chat.limitReached": "Message limit reached",
    "chat.limitReachedDesc": "You've reached the limit of {{limit}} daily messages on the Basic plan. Upgrade to Intermediate plan for unlimited chat.",
    "chat.messagesUsed": "Messages used today",
    "chat.messagesLimit": "of {{limit}} daily",
    "chat.unlimited": "unlimited",
    "chat.welcome": "Hello! I'm your AI nutrition coach. How can I help you today?",
    "chat.errorSending": "Error sending message",
    "chat.errorSendingDesc": "Please try again",
    
    // Privacy & Terms
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated",
    "privacy.back": "Back",
    "terms.title": "Terms and Conditions",
    "terms.lastUpdated": "Last updated",
    "terms.back": "Back",
    
    // NotFound
    "notfound.title": "404",
    "notfound.heading": "Page not found",
    "notfound.message": "Sorry, the page you're looking for doesn't exist or has been moved.",
    "notfound.goBack": "Go back",
    "notfound.goHome": "Go home",
    
    // Meal Detail
    "mealDetail.nutritionalInfo": "Nutritional Information",
    "mealDetail.calories": "Calories",
    "mealDetail.protein": "Protein",
    "mealDetail.carbs": "Carbohydrates",
    "mealDetail.fats": "Fats",
    "mealDetail.benefits": "Benefits",
    "mealDetail.ingredients": "Ingredients",
    "mealDetail.steps": "Cooking Steps",
    "mealDetail.swapMeal": "Swap meal",
    "mealDetail.lockedMessage": "You need to be subscribed to swap meals",
    "mealDetail.breakfast": "Breakfast",
    "mealDetail.lunch": "Lunch",
    "mealDetail.dinner": "Dinner",
    
    // Swap Meal
    "swapMeal.title": "Swap meal",
    "swapMeal.description": "Select which meal you want to swap with",
    
    // Challenges
    "challenges.title": "Daily Challenges",
    "challenges.subtitle": "Complete challenges to earn extra points",
    "challenges.noChallenges": "No active challenges",
    "challenges.generateNew": "Generate new challenges",
    "challenges.generating": "Generating...",
    "challenges.errorLoading": "Could not load challenges",
    "challenges.errorGenerating": "Could not generate challenges",
    "challenges.challengesGenerated": "Challenges generated!",
    "challenges.newChallenges": "You have 3 new daily challenges",
    "challenges.complete": "Complete",
    "challenges.completed": "Completed!",
    "challenges.progress": "Progress",
    "challenges.reward": "Reward",
    "challenges.bonus": "Bonus",
    "challenges.points": "points",
    
    // Achievements
    "achievements.title": "Achievements and Badges",
    "achievements.subtitle": "Unlock badges by completing challenges",
    "achievements.unlocked": "Unlocked",
    "achievements.points": "pts",
    
    // Nutrition Charts
    "nutritionCharts.title": "Nutritional Progress",
    "nutritionCharts.subtitle": "Visualize your evolution over time",
    "nutritionCharts.weekly": "Weekly (28 days)",
    "nutritionCharts.monthly": "Monthly (12 weeks)",
    "nutritionCharts.calories": "Calories",
    "nutritionCharts.protein": "Protein",
    "nutritionCharts.carbs": "Carbohydrates",
    "nutritionCharts.fats": "Fats",
    "nutritionCharts.mealsCompleted": "Meals Completed",
    "nutritionCharts.noData": "No data available yet. Complete meals to see your progress.",
    
    // Confirm Plan
    "confirmPlan.title": "Generate new weekly plan?",
    "confirmPlan.description": "This will replace your current plan. Choose how you want to generate your new menu:",
    "confirmPlan.cached": "Use existing menu (Recommended)",
    "confirmPlan.cachedDesc": "Reuse a menu with your same preferences. Doesn't consume AI credits. ✨",
    "confirmPlan.new": "Generate completely new menu",
    "confirmPlan.newDesc": "Create a unique menu with AI. Consumes Lovable AI credits. 🤖",
    "confirmPlan.cancel": "Cancel",
    "confirmPlan.generate": "Generate plan",
    "confirmPlan.generating": "Generating...",
    
    // Daily Summary
    "dailySummary.title": "Day Completed!",
    "dailySummary.subtitle": "Nutritional summary for",
    "dailySummary.congrats": "Excellent work completing all your meals for the day!",
    "dailySummary.totalCalories": "Total Calories",
    "dailySummary.kcal": "kcal",
    "dailySummary.proteins": "Protein",
    "dailySummary.carbohydrates": "Carbohydrates",
    "dailySummary.fats": "Fats",
    "dailySummary.motivational": "Keep up this pace to reach your health goals 💪",
    
    // Celebration Messages
    "dashboard.celebrationMessages": ["Excellent! 🎉", "Keep it up! 💪", "Amazing! ⭐", "You're the best! 🏆", "What a pro! 🔥"],
    
    // Subscription Banner
    "subscription.activePlan": "Plan",
    "subscription.active": "Active",
    "subscription.managePlan": "Manage plan",
    "subscription.enjoyBenefits": "Enjoy all the benefits of your plan",
    "subscription.trialExpiring": "Your trial period is about to expire",
    "subscription.daysRemaining": "days remaining",
    "subscription.oneDay": "Only 1 day left!",
    "subscription.subscribeNow": "Subscribe now",
    "subscription.upgradePrompt": "Subscribe to continue enjoying all features",
    
    // Demo
    "demo.badge": "Interactive demo",
    "demo.title": "Discover how it works",
    "demo.subtitle": "Follow the complete flow from your signup to your first personalized meal plan",
    "demo.startDemo": "Start Demo",
    "demo.restart": "Restart Demo",
    "demo.step1Title": "Step 1: Welcome",
    "demo.step1Desc": "We start by learning your goals",
    "demo.step2Title": "Step 2: Preferences",
    "demo.step2Desc": "We personalize your experience",
    "demo.step3Title": "Step 3: AI Generation",
    "demo.step3Desc": "We create your personalized plan",
    "demo.step4Title": "Step 4: Your Dashboard",
    "demo.step4Desc": "Access your plan and features",
    
    // Achievement Unlock
    "achievementUnlock.unlocked": "Achievement Unlocked!",
    "achievementUnlock.earned": "You have earned",
    "achievementUnlock.clickToContinue": "Click to continue",
    
    // Blog
    "blog.title": "Nutrition Blog",
    "blog.subtitle": "Tips, recipes and guides for a healthy life",
    "blog.readMore": "Read more",
    "blog.backToBlog": "Back to blog",
    "blog.relatedArticles": "Related articles",
    "blog.shareArticle": "Share article",
    "blog.article1.title": "Complete Guide: Meal Planning for Sustainable Weight Loss",
    "blog.article1.excerpt": "Discover scientifically proven strategies to plan your meals and achieve your weight goals in a healthy and lasting way.",
    "blog.article1.content": [
      "Meal planning is one of the most powerful tools for achieving sustainable weight loss. It's not just about counting calories, but creating a system that allows you to make nutritious decisions consistently.",
      "## Why is meal planning important?",
      "Planning eliminates impulsive decision-making when you're hungry, reduces food-related stress, and helps you maintain balanced nutrition. Studies show that people who plan their meals have a 50% higher success rate in maintaining their ideal weight.",
      "## Basic principles of nutritional planning",
      "**1. Macronutrient balance:** Make sure to include lean proteins, complex carbohydrates, and healthy fats in every meal. The ideal proportion varies according to your goals, but a general guide is 40% carbohydrates, 30% protein, and 30% fat.",
      "**2. Advance preparation:** Dedicate 2-3 hours on Sundays to prepare basic ingredients like brown rice, grilled chicken, cut vegetables, and cooked legumes. This will facilitate meal assembly during the week.",
      "**3. Nutritional variety:** Include foods of all colors of the rainbow to ensure a wide range of vitamins, minerals, and antioxidants. Diversity also prevents food boredom.",
      "## Practical strategies for success",
      "**Batch cooking:** Cook large quantities of proteins and grains once a week. This saves you time and ensures you always have healthy options available.",
      "**Container system:** Use clear glass containers to visualize your prepared meals. Label them with the day and meal type for better organization.",
      "**Smart snacks:** Prepare individual portions of fruits, nuts, and vegetables to avoid excessive consumption and always have healthy options at hand.",
      "## Example of a balanced weekly plan",
      "**Monday:**\n- Breakfast: Oatmeal with berries and almonds\n- Lunch: Quinoa salad with chicken and avocado\n- Dinner: Baked salmon with broccoli and sweet potato",
      "**Tuesday:**\n- Breakfast: Green smoothie with spinach, banana, and protein\n- Lunch: Brown rice bowl with tofu and sautéed vegetables\n- Dinner: Turkey breast with mixed salad and nuts",
      "**Wednesday:**\n- Breakfast: Scrambled eggs with whole wheat toast and avocado\n- Lunch: Lentil soup with vegetables\n- Dinner: White fish with asparagus and quinoa",
      "## Common mistakes to avoid",
      "**1. Planning overly restrictive meals:** This leads to cravings and plan abandonment. Include your favorite foods in moderation.",
      "**2. Not considering your lifestyle:** If you travel frequently or have irregular schedules, adapt your plan to your reality.",
      "**3. Ignoring hunger signals:** Planning doesn't mean absolute rigidity. Learn to listen to your body and adjust as needed.",
      "## Useful tools and resources",
      "Apps like Chefly.AI can help you generate personalized plans based on your preferences, dietary restrictions, and goals. Artificial intelligence can suggest recipes, create shopping lists, and adjust portions according to your needs.",
      "## Conclusion",
      "Meal planning is a skill that improves with practice. Start with small steps: plan only your dinners for the week or prepare your breakfasts in advance. Over time, you'll develop a system that works perfectly for you and brings you closer to your health goals in a sustainable way.",
      "Remember: the best plan is one you can maintain long-term. Be flexible, patient with yourself, and celebrate every small progress on your path to a healthier life."
    ],
    "blog.article1.tags": ["weight loss", "planning", "nutrition", "meal prep"],
    "blog.article1.readTime": "8 min",
    "blog.article1.date": "January 24, 2025",
    "blog.article1.author": "Eduardo Zermeño",

    // Affiliate Program Banner
    "affiliateBanner.badge": "Earn Extra Money",
    "affiliateBanner.title": "Join the",
    "affiliateBanner.titleHighlight": "Affiliate Program",
    "affiliateBanner.titleEnd": "at Chefly!",
    "affiliateBanner.description": "Recommend Chefly and earn up to",
    "affiliateBanner.commission": "25% commission",
    "affiliateBanner.descriptionEnd": "per sale. 100% free, no membership fees.",
    "affiliateBanner.feature1Title": "20-25% commission",
    "affiliateBanner.feature1Desc": "Per referred sale",
    "affiliateBanner.feature2Title": "Bi-weekly payments",
    "affiliateBanner.feature2Desc": "Minimum withdrawal of $200 MXN",
    "affiliateBanner.feature3Title": "Real-time dashboard",
    "affiliateBanner.feature3Desc": "Statistics and marketing tools",
    "affiliateBanner.cta": "Start Now",
    "affiliateBanner.commissionsMonth": "Commissions this month",
    "affiliateBanner.salesMonth": "Sales this month",
    "affiliateBanner.level": "Level",
    "affiliateBanner.levelProgress": "to level",

    // Affiliate Payout Method Setup
    "affiliatePayoutMethod.configured": "Payout Method Configured",
    "affiliatePayoutMethod.allSet": "All set!",
    "affiliatePayoutMethod.allSetDesc": "You can request withdrawals when you have at least $200 MXN available. Payments will be processed manually by our team within 1-3 business days.",
    "affiliatePayoutMethod.setup": "Setup Payout Method",
    "affiliatePayoutMethod.setupDesc": "Configure your preferred payout method to receive commissions",
    "affiliatePayoutMethod.configRequired": "Configuration required",
    "affiliatePayoutMethod.configRequiredDesc": "Add your payment information when making your first withdrawal request. You can choose between PayPal, bank transfer, or SPEI.",
    "affiliatePayoutMethod.available": "Available methods:",
    "affiliatePayoutMethod.paypal": "PayPal - Fast withdrawals",
    "affiliatePayoutMethod.bankTransfer": "Bank Transfer - To your bank account",
    "affiliatePayoutMethod.spei": "SPEI - Instant transfer in Mexico",

    // Affiliate Payout Request
    "affiliatePayoutRequest.title": "Withdraw Balance",
    "affiliatePayoutRequest.available": "Available",
    "affiliatePayoutRequest.processTime": "Processed in 1-3 business days",
    "affiliatePayoutRequest.amount": "Withdrawal Amount (MXN)",
    "affiliatePayoutRequest.amountPlaceholder": "Minimum $",
    "affiliatePayoutRequest.method": "Payout Method",
    "affiliatePayoutRequest.methodPaypal": "PayPal",
    "affiliatePayoutRequest.methodBank": "Bank Transfer",
    "affiliatePayoutRequest.methodSpei": "SPEI",
    "affiliatePayoutRequest.submit": "Request withdrawal",
    "affiliatePayoutRequest.submitting": "Sending request...",
    "affiliatePayoutRequest.minRequired": "You need at least",
    "affiliatePayoutRequest.minRequiredEnd": "to request a payment",
    "affiliatePayoutRequest.insufficientAmount": "Insufficient amount",
    "affiliatePayoutRequest.insufficientAmountDesc": "The minimum withdrawal amount is $",
    "affiliatePayoutRequest.insufficientBalance": "Insufficient balance",
    "affiliatePayoutRequest.insufficientBalanceDesc": "You don't have enough available balance",
    "affiliatePayoutRequest.success": "Request sent!",
    "affiliatePayoutRequest.successDesc": "Your withdrawal request for ${{amount}} MXN has been sent. Our team will process it within 1-3 business days.",
    "affiliatePayoutRequest.error": "Error",

    // Affiliate Tier Names
    "affiliateTier.bronce": "Bronze",
    "affiliateTier.plata": "Silver",
    "affiliateTier.oro": "Gold",
    "affiliateTier.platino": "Platinum",
    "affiliateTier.diamante": "Diamond",

    // Affiliates Landing
    "affiliatesLanding.nav.home": "Home",
    "affiliatesLanding.nav.login": "Login",
    "affiliatesLanding.hero.badge": "Verified and Trusted Program",
    "affiliatesLanding.hero.title": "Chefly Affiliate Program",
    "affiliatesLanding.hero.subtitle": "Earn money by sharing the best AI-powered personalized nutrition platform",
    "affiliatesLanding.hero.cta": "Join Now - It's Free",
    "affiliatesLanding.hero.seeHow": "See How It Works",
    "affiliatesLanding.stats.activeAffiliates": "Active Affiliates",
    "affiliatesLanding.stats.paidOut": "Paid to Affiliates",
    "affiliatesLanding.stats.sales": "Sales Generated",
    "affiliatesLanding.stats.satisfaction": "Satisfaction Rate",
    "affiliatesLanding.guarantees.payments": "Guaranteed Payments",
    "affiliatesLanding.guarantees.paymentsDesc": "Timely payments every time you request. No tricks or fine print.",
    "affiliatesLanding.guarantees.security": "Secure Data",
    "affiliatesLanding.guarantees.securityDesc": "Banking and payment information protected with bank-level encryption.",
    "affiliatesLanding.guarantees.speed": "Fast Processing",
    "affiliatesLanding.guarantees.speedDesc": "Payments processed in 3-5 business days maximum.",
    "affiliatesLanding.guarantees.transparency": "Total Transparency",
    "affiliatesLanding.guarantees.transparencyDesc": "Dashboard with real-time metrics. Always know how much you've earned.",
    "affiliatesLanding.commissions.title": "Commission Structure",
    "affiliatesLanding.commissions.subtitle": "Earn competitive commissions for every subscription you generate",
    "affiliatesLanding.commissions.commission": "Commission",
    "affiliatesLanding.commissions.earning": "You earn per sale",
    "affiliatesLanding.benefits.title": "Program Benefits",
    "affiliatesLanding.benefits.subtitle": "All the tools you need to succeed as an affiliate",
    "affiliatesLanding.benefits.attractive": "Attractive Commissions",
    "affiliatesLanding.benefits.attractiveDesc": "Earn up to 25% commission for each sale you generate",
    "affiliatesLanding.benefits.timely": "Timely Payments",
    "affiliatesLanding.benefits.timelyDesc": "Withdraw your earnings when you reach the $200 MXN minimum",
    "affiliatesLanding.benefits.dashboard": "Complete Dashboard",
    "affiliatesLanding.benefits.dashboardDesc": "Monitor your clicks, conversions and earnings in real time",
    "affiliatesLanding.benefits.easy": "Easy to Use",
    "affiliatesLanding.benefits.easyDesc": "Get your personalized link and start earning in minutes",
    "affiliatesLanding.tiers.title": "Tier System",
    "affiliatesLanding.tiers.subtitle": "Level up and increase your commissions as you generate more sales",
    "affiliatesLanding.tiers.bonus": "bonus",
    "affiliatesLanding.tiers.progress": "Progress automatically!",
    "affiliatesLanding.tiers.progressDesc": "Your level updates automatically when you reach the requirements",
    "affiliatesLanding.howItWorks.title": "How It Works?",
    "affiliatesLanding.howItWorks.subtitle": "Start earning in 4 simple steps",
    "affiliatesLanding.testimonials.title": "Success Stories",
    "affiliatesLanding.testimonials.subtitle": "Real affiliates sharing their results",
    "affiliatesLanding.faq.title": "Frequently Asked Questions",
    "affiliatesLanding.faq.subtitle": "Everything you need to know about the program",
    "affiliatesLanding.cta.title": "Ready to Start?",
    "affiliatesLanding.cta.subtitle": "Join hundreds of affiliates who are already earning with Chefly",
    "affiliatesLanding.cta.button": "Start Now",
    "affiliatesLanding.cta.info": "Need more information?",
    "affiliatesLanding.cta.contact": "Contact us",

    // Affiliates Login
    "affiliatesLogin.title": "Affiliate Portal",
    "affiliatesLogin.subtitle": "Log in or create your account to access the dashboard",
    "affiliatesLogin.alert": "If you're not yet an affiliate, first create your account and then complete the affiliate registration.",
    "affiliatesLogin.tabLogin": "Log In",
    "affiliatesLogin.tabSignup": "Create Account",
    "affiliatesLogin.loginTitle": "Log In",
    "affiliatesLogin.loginDesc": "Access your affiliate account",
    "affiliatesLogin.signupTitle": "Create Account",
    "affiliatesLogin.signupDesc": "Create your account to register as an affiliate",
    "affiliatesLogin.email": "Email",
    "affiliatesLogin.password": "Password",
    "affiliatesLogin.confirmPassword": "Confirm Password",
    "affiliatesLogin.loginButton": "Log In",
    "affiliatesLogin.loggingIn": "Logging in...",
    "affiliatesLogin.signupButton": "Create Account and Continue",
    "affiliatesLogin.creatingAccount": "Creating account...",
    "affiliatesLogin.moreInfo": "Need more information?",
    "affiliatesLogin.error.required": "Required fields",
    "affiliatesLogin.error.requiredDesc": "Please complete all fields",
    "affiliatesLogin.error.noMatch": "Passwords don't match",
    "affiliatesLogin.error.noMatchDesc": "Please verify both passwords are the same",
    "affiliatesLogin.error.short": "Password too short",
    "affiliatesLogin.error.shortDesc": "Password must be at least 6 characters",
    "affiliatesLogin.error.notAffiliate": "Not an affiliate",
    "affiliatesLogin.error.notAffiliateDesc": "This account is not registered as an affiliate. Please register first.",
    "affiliatesLogin.success.welcome": "Welcome!",
    "affiliatesLogin.success.welcomeDesc": "Login successful",
    "affiliatesLogin.success.created": "Account created!",
    "affiliatesLogin.success.createdDesc": "Now complete your affiliate registration",

    // Affiliates Register
    "affiliatesRegister.title": "Affiliate Registration",
    "affiliatesRegister.subtitle": "Complete the form to join the affiliate program",
    "affiliatesRegister.alert": "You need to log in to register as an affiliate.",
    "affiliatesRegister.alertLink": "Log in here",
    "affiliatesRegister.fullName": "Full Name",
    "affiliatesRegister.email": "Email",
    "affiliatesRegister.phone": "Phone",
    "affiliatesRegister.country": "Country",
    "affiliatesRegister.paymentTitle": "Payment Method",
    "affiliatesRegister.paymentMethod": "Preferred Method",
    "affiliatesRegister.paypalEmail": "PayPal Email",
    "affiliatesRegister.bank": "Bank",
    "affiliatesRegister.bankAccount": "Account Number",
    "affiliatesRegister.clabe": "CLABE Interbank Code",
    "affiliatesRegister.commissionsTitle": "Commissions:",
    "affiliatesRegister.basicPlan": "Basic Plan: 20% commission ($48 MXN per sale)",
    "affiliatesRegister.intermediatePlan": "Intermediate Plan: 25% commission ($72.50 MXN per sale)",
    "affiliatesRegister.minPayout": "Minimum payout: $200 MXN",
    "affiliatesRegister.payoutFrequency": "Payments processed every 15 days",
    "affiliatesRegister.submit": "Submit Application",
    "affiliatesRegister.processing": "Processing...",
    "affiliatesRegister.error.loginFirst": "Log in first",
    "affiliatesRegister.error.loginFirstDesc": "You need to create an account or log in to register as an affiliate",
    "affiliatesRegister.success.submitted": "Application submitted!",
    "affiliatesRegister.success.submittedDesc": "Your application will be reviewed in 1-2 business days",

    // Affiliate Marketing Materials
    "affiliateMarketing.title": "Marketing Materials",
    "affiliateMarketing.subtitle": "Download banners and copy ready-to-use promotional texts",
    "affiliateMarketing.banners": "HTML Banners",
    "affiliateMarketing.copyCode": "Copy code",
    "affiliateMarketing.texts": "Promotional Texts",
    "affiliateMarketing.copyText": "Copy text",
    "affiliateMarketing.copied": "Copied!",
    "affiliateMarketing.copiedDesc": "Text has been copied to clipboard",
    "affiliateMarketing.textShort": "Promotional Text - Short",
    "affiliateMarketing.textLong": "Promotional Text - Long",
    "affiliateMarketing.socialPost": "Social Media Post",

    // Onboarding
    "onboarding.title": "Customize your experience",
    "onboarding.subtitle": "Tell us about yourself to create your perfect plan",
    "onboarding.step": "Step {{current}} of {{total}}",
    "onboarding.description": "This information will help us personalize your menus",
    
    "onboarding.goal.title": "What is your main goal?",
    "onboarding.goal.loseFat": "Lose fat",
    "onboarding.goal.gainMuscle": "Gain muscle",
    "onboarding.goal.eatHealthy": "Eat healthy",
    "onboarding.goal.saveMoney": "Save money",
    
    "onboarding.diet.title": "What type of diet do you prefer?",
    "onboarding.diet.omnivore": "Omnivore",
    "onboarding.diet.vegetarian": "Vegetarian",
    "onboarding.diet.vegan": "Vegan",
    "onboarding.diet.keto": "Keto",
    "onboarding.diet.paleo": "Paleo",
    
    "onboarding.activity.title": "What is your physical activity level?",
    "onboarding.activity.description": "This helps us better calculate your caloric needs",
    "onboarding.activity.sedentary": "Sedentary - Little to no exercise",
    "onboarding.activity.light": "Light - Exercise 1-2 days/week",
    "onboarding.activity.moderate": "Moderate - Exercise 3-5 days/week",
    "onboarding.activity.active": "Active - Exercise 6-7 days/week",
    "onboarding.activity.veryActive": "Very active - Intense daily exercise",
    
    "onboarding.personal.title": "Personal information (optional)",
    "onboarding.personal.description": "This helps us better calculate your nutritional needs",
    "onboarding.personal.age": "Age",
    "onboarding.personal.agePlaceholder": "Ex: 25",
    "onboarding.personal.weight": "Weight (kg)",
    "onboarding.personal.weightPlaceholder": "Ex: 70",
    "onboarding.personal.gender": "Gender",
    "onboarding.personal.male": "Male",
    "onboarding.personal.female": "Female",
    "onboarding.personal.other": "Other",
    
    "onboarding.cooking.title": "What is your cooking experience level?",
    "onboarding.cooking.beginner": "Beginner - Simple recipes",
    "onboarding.cooking.intermediate": "Intermediate - I can follow most recipes",
    "onboarding.cooking.advanced": "Advanced - I enjoy cooking complex dishes",
    
    "onboarding.budget.title": "What is your food budget?",
    "onboarding.budget.low": "Low - Budget ingredients",
    "onboarding.budget.medium": "Medium - Balance between price and quality",
    "onboarding.budget.high": "High - Premium ingredients",
    "onboarding.time.title": "How much time can you cook per meal? (minutes)",
    "onboarding.time.minutes": "{{time}} minutes",
    
    "onboarding.meals.title": "How many meals do you eat per day?",
    "onboarding.meals.count": "{{count}} meals",
    "onboarding.servings.title": "How many people do you cook for?",
    "onboarding.servings.person": "{{count}} person",
    "onboarding.servings.people": "{{count}} people",
    "onboarding.complexityTitle": "Recipe complexity",
    "onboarding.complexitySimple": "Simple - Few steps and ingredients",
    "onboarding.complexityModerate": "Moderate - Standard recipes",
    "onboarding.complexityComplex": "Complex - Elaborate recipes",
    
    "onboarding.flavors.title": "What flavors do you like?",
    "onboarding.flavors.description": "Select all that apply",
    "onboarding.flavor.sweet": "Sweet",
    "onboarding.flavor.salty": "Salty",
    "onboarding.flavor.spicy": "Spicy",
    "onboarding.flavor.sour": "Sour",
    "onboarding.flavor.umami": "Umami",
    "onboarding.flavor.bitter": "Bitter",
    
    "onboarding.cuisines.title": "What types of cuisine do you prefer?",
    "onboarding.cuisines.description": "Select all you like",
    "onboarding.cuisine.mexican": "Mexican",
    "onboarding.cuisine.italian": "Italian",
    "onboarding.cuisine.asian": "Asian",
    "onboarding.cuisine.mediterranean": "Mediterranean",
    "onboarding.cuisine.american": "American",
    "onboarding.cuisine.vegetarian": "Vegetarian",
    "onboarding.cuisine.healthy": "Healthy",
    
    "onboarding.allergies.title": "Do you have any allergies?",
    "onboarding.allergies.description": "Helps us avoid these ingredients",
    "onboarding.allergies.placeholder": "Ex: Lactose, gluten, nuts...",
    "onboarding.allergies.add": "Add",
    "onboarding.allergies.tooLong": "Entry too long",
    "onboarding.allergies.tooLongDesc": "Allergy cannot be more than 100 characters",
    "onboarding.allergies.invalid": "Invalid entry",
    "onboarding.allergies.invalidDesc": "Only letters and spaces are allowed",
    
    "onboarding.dislikes.title": "Are there any ingredients you don't like?",
    "onboarding.dislikes.description": "Optional - Helps us personalize better",
    "onboarding.dislikes.placeholder": "Ex: Broccoli, cilantro, mushrooms...",
    "onboarding.notes.title": "Additional comments (optional)",
    "onboarding.notes.placeholder": "Anything else we should know? Ex: Preferred schedules, favorite foods, etc.",
    
    "onboarding.buttons.back": "Back",
    "onboarding.buttons.next": "Next",
    "onboarding.buttons.creating": "Saving...",
    "onboarding.buttons.create": "Create my personalized plan",
    
    "onboarding.toast.requiredFields": "Required fields",
    "onboarding.toast.requiredFieldsDesc": "Please complete all required fields",
    "onboarding.toast.perfect": "Perfect!",
    "onboarding.toast.generating": "Generating your first personalized weekly menu...",
    "onboarding.toast.errorGenerating": "Error generating menu",
    "onboarding.toast.errorGeneratingDesc": "You can generate it manually from the dashboard",
    "onboarding.toast.created": "Menu created!",
    "onboarding.toast.createdDesc": "Your personalized weekly plan is ready",
    "onboarding.toast.error": "Error",
    
    // Cookies
    "cookies.message": "We use cookies to analyze traffic and improve your experience.",
    "cookies.accept": "Accept",
    "cookies.decline": "Decline",
    "cookies.learnMore": "Learn more",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "en" || saved === "es") ? saved : "es";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const value = translations[language][key as keyof typeof translations.es];
    let translation = Array.isArray(value) ? key : (value || key);
    
    if (params && typeof translation === 'string') {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{{${param}}}`, String(params[param]));
      });
    }
    
    return translation;
  };

  const getArray = (key: string): string[] => {
    const value = translations[language][key as keyof typeof translations.es];
    return Array.isArray(value) ? value : [];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getArray }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
