-- Add ingredients and steps to meals table
ALTER TABLE meals 
ADD COLUMN IF NOT EXISTS ingredients TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS steps TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS calories INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS protein INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS carbs INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fats INTEGER DEFAULT 0;